ein paar Fehler beheben
nove-org/NAPI pull request #102
Opened 2023-08-31 21:24 UTC by Dawid-03

## Changes

-   resolved #101

2023-08-31 21:59 UTC, ArsBeneMoriendi submitted a review, later dismissed

2023-09-01 07:26 UTC, wnm210 requested changes
The `emailReset.ts` file is not imported in the index so it cannot be reached.

2023-09-01 07:26 UTC, wnm210 commented on src/routes/v1/users/me.ts
> +    return res.redirect(process.env.FRONTEND_URL as string);
Should return something like `success: true` instead of redirecting to frontend because this endpoint will be used by fetching it from the code, not redirecting user to it.

2023-09-01 07:26 UTC, wnm210 commented on src/routes/v1/users/me.ts
> +router.delete('/me', authorize({ disableBearer: true }), async (req: Request, res: Response) => {
We should ask for password confirmation for security reasons when deleting the account.

2023-09-04 11:29 UTC, merged